### ISSUE TITLE
make user error

### ISSUE THREAD

**Issue by aogrcs** [SEL4PROJ/seL4-CAmkES-L4v-dockerfiles#2]
When I used "make user", the error was:

useradd: user 'root' already exists
Makefile:284: recipe for target 'build_user' failed
make: *** [build_user] Error 9

I used Ubuntu 16.04 for x86_64, thanks!
Sincerely

**Comment by LukeMondy** [comment]
Hello,

Are you running the containers as root or with `sudo`? Try running the `make` commands under your normal user account.

If you are using the root account or sudo because you can't run docker commands from your normal terminal, I would advise adding yourself to the `docker` group like this:

`sudo usermod -aG docker ${your_username}`

and then logout and re-log back in. Then you should be able to use docker under your own account.

If this doesn't help, please let me know.

**Comment by aogrcs** [comment]
Hi,
Yes, I used sudo. If used make, then I did not have permission.
I tested sudo usermod -aG docker talos then docker logout, it said:

Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Not logged in to https://index.docker.io/v1/

So I did sudo docker logout, it said
Not logged in to https://index.docker.io/v1/

**Comment by aogrcs** [comment]
Hi,
I restart the computer, it did work! Thanks
