### ISSUE TITLE
Test l4v/HaskellKernel fails

### ISSUE THREAD

**Issue by paolo-crisafulli** [SEL4PROJ/seL4-CAmkES-L4v-dockerfiles#8]
Hi,
When l4v/run_tests is run, the test named HaskellKernel fails.
This is due to cabal not being installed, according to the test log.
Indeed, ghc and cabal install section are commented out in l4v.dockerfile.
When uncommented, ghc install succeeds but cabal install fails.
Is this something you also experiment and is there a way to fix it?
Thank you very much in advance.
Best regards,
Paolo Crisafulli

**Comment by LukeMondy** [comment]
Can you paste the error that the HaskellKernel test dumps out?

Looking through all the files, it *should* be OK, because in the dockerfile, we run `make sandbox` in the `l4v/spec/haskell` directory, which *should* tell stack to go get the right GHC and Cabal version.

Clearly something isn't quite right though.

**Comment by paolo-crisafulli** [comment]
I have pulled the latest l4v image, rebuilt the user l4v image and the test now passes.
AFAIC, I think you can close the issue.
Thank you, sorry for the disturbance!

**Comment by LukeMondy** [comment]
Cool! I added $HOME/.local/bin to the path (as stack recommends), so hopefully that was all that was needed.
